spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true